create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0 and char_length(title) <= 140),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

drop policy if exists "public can read todos" on public.todos;
drop policy if exists "public can create todos" on public.todos;
drop policy if exists "public can update todos" on public.todos;
drop policy if exists "public can delete todos" on public.todos;

create policy "public can read todos"
on public.todos
for select to anon
using (true);

create policy "public can create todos"
on public.todos
for insert to anon
with check (true);

create policy "public can update todos"
on public.todos
for update to anon
using (true)
with check (true);

create policy "public can delete todos"
on public.todos
for delete to anon
using (true);
